FORMAT: 1A
HOST: http://founderytoolcontrolapi.apiblueprint.org/

# foundery-tool-control-api

Authorization for Foundery Tools

## User Authorizations [/authorization_requests]

### Create an Authorization Request [POST]

You may create an authorization request using this action. It takes a JSON object
containing a user's assigned RFID tag, the tool id, and an hardware preshared key.

+ user_rfid (number) - The user's RFID tag number.
+ tool_id (number) - A unique tool ID configured on the hardware.
+ secret_key (string) - A preshared access key stored on the hardware.

+ Request (application/json)

{
    "user_rfid": 123546845,
    "tool_id": 245,
    "auth_key":"2jl34kj23lk4j23k423j"
}

+ Response 201 (application/json)

{
    "tool_authorized": true,
    "power_off_delay_seconds": 360,
}